/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "ff_yosys.v:4" *)
module FF(CLK, EN, D, Q);
  (* src = "ff_yosys.v:15" *)
  wire _0_;
  (* src = "ff_yosys.v:6" *)
  input CLK;
  (* src = "ff_yosys.v:8" *)
  input D;
  (* src = "ff_yosys.v:7" *)
  input EN;
  (* src = "ff_yosys.v:9" *)
  output Q;
  reg Q;
  assign _0_ = EN ? (* src = "ff_yosys.v:16" *) D : Q;
  (* src = "ff_yosys.v:15" *)
  always @(posedge CLK)
      Q <= _0_;
endmodule

(* src = "contador.v:3" *)
module contador(CLK, ENB, MODO, D, Q, RCO);
  (* src = "contador.v:22" *)
  wire _000_;
  (* src = "contador.v:22" *)
  wire _001_;
  (* src = "contador.v:22" *)
  wire _002_;
  (* src = "contador.v:25" *)
  (* unused_bits = "4" *)
  wire [31:0] _003_;
  wire _004_;
  wire [1:0] _005_;
  wire [1:0] _006_;
  wire [1:0] _007_;
  wire _008_;
  wire _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire _016_;
  wire _017_;
  wire [3:0] _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  (* src = "contador.v:42" *)
  wire _027_;
  (* src = "contador.v:42" *)
  wire _028_;
  (* src = "contador.v:42" *)
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:432" *)
  wire [2:0] _034_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:428" *)
  wire _035_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:432" *)
  wire [15:0] _036_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:428" *)
  wire [3:0] _037_;
  (* src = "contador.v:33" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _038_;
  (* src = "contador.v:41" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _039_;
  (* src = "contador.v:25|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _040_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)
  wire _041_;
  (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)
  wire _042_;
  (* src = "contador.v:33|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _043_;
  (* src = "contador.v:41|contador.v:33|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _044_;
  (* src = "contador.v:33|<techmap.v>:260|<techmap.v>:221" *)
  wire _045_;
  (* src = "contador.v:33|<techmap.v>:260|<techmap.v>:229" *)
  wire _046_;
  (* src = "contador.v:41|contador.v:33|<techmap.v>:260|<techmap.v>:229" *)
  wire _047_;
  (* src = "contador.v:4" *)
  input CLK;
  (* src = "contador.v:7" *)
  input [3:0] D;
  (* src = "contador.v:5" *)
  input ENB;
  (* src = "contador.v:6" *)
  input [1:0] MODO;
  (* src = "contador.v:8" *)
  output [3:0] Q;
  (* src = "contador.v:9" *)
  output RCO;
  (* init = 4'h0 *)
  (* src = "contador.v:12" *)
  wire [3:0] d_In;
  (* src = "contador.v:13" *)
  wire d_Out;
  assign _004_ = _033_ | _030_;
  assign _005_[0] = _003_[0] |(* src = "contador.v:42" *)  Q[1];
  assign _021_ = _005_[0] |(* src = "contador.v:42" *)  _005_[1];
  assign _006_[0] = Q[0] |(* src = "contador.v:42" *)  _018_[1];
  assign _005_[1] = Q[2] |(* src = "contador.v:42" *)  Q[3];
  assign _022_ = _006_[0] |(* src = "contador.v:42" *)  _005_[1];
  assign _007_[0] = _003_[0] |(* src = "contador.v:49" *)  _018_[1];
  assign _007_[1] = _019_[2] |(* src = "contador.v:49" *)  _019_[3];
  assign _023_ = _007_[0] |(* src = "contador.v:49" *)  _007_[1];
  assign _024_ = _020_[0] |(* src = "contador.v:48|contador.v:23" *)  _020_[1];
  assign _025_ = MODO[0] |(* src = "contador.v:41|contador.v:23" *)  _020_[1];
  assign _026_ = _020_[0] |(* src = "contador.v:33|contador.v:23" *)  MODO[1];
  assign _008_ = _034_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _034_[1];
  assign _035_ = _008_ |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _034_[2];
  assign _009_ = _004_ |(* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)  _031_;
  assign _041_ = _009_ |(* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)  _032_;
  assign _010_[0] = _036_[1] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[5];
  assign _010_[1] = _036_[9] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[13];
  assign _037_[1] = _010_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _010_[1];
  assign _011_[0] = _036_[3] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[7];
  assign _011_[1] = _036_[11] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[15];
  assign _037_[3] = _011_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _011_[1];
  assign _012_[0] = _036_[2] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[6];
  assign _012_[1] = _036_[10] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[14];
  assign _037_[2] = _012_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _012_[1];
  assign _013_[0] = _036_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[4];
  assign _013_[1] = _036_[8] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _036_[12];
  assign _037_[0] = _013_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:441" *)  _013_[1];
  assign _014_[0] = _030_ |(* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)  _031_;
  assign _014_[1] = _032_ |(* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)  _033_;
  assign _042_ = _014_[0] |(* src = "contador.v:48|contador.v:23|<techmap.v>:445" *)  _014_[1];
  assign _015_[0] = Q[0] |(* src = "contador.v:42" *)  Q[1];
  assign _016_ = _015_[0] |(* src = "contador.v:42" *)  _005_[1];
  assign _017_ = MODO[0] |(* src = "contador.v:25|contador.v:23" *)  MODO[1];
  assign _001_ = ~(* src = "contador.v:42" *) _016_;
  assign _027_ = ~(* src = "contador.v:42" *) _021_;
  assign _028_ = ~(* src = "contador.v:42" *) _022_;
  assign _000_ = ~(* src = "contador.v:49" *) _023_;
  assign _030_ = ~(* src = "contador.v:48|contador.v:23" *) _024_;
  assign _031_ = ~(* src = "contador.v:41|contador.v:23" *) _025_;
  assign _032_ = ~(* src = "contador.v:33|contador.v:23" *) _026_;
  assign _033_ = ~(* src = "contador.v:25|contador.v:23" *) _017_;
  assign _029_ = _001_ |(* src = "contador.v:42" *)  _027_;
  assign _002_ = _029_ |(* src = "contador.v:42" *)  _028_;
  assign d_Out = _041_ ? (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *) _035_ : 1'hx;
  assign d_In[0] = _042_ ? (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *) _037_[0] : 1'hx;
  assign d_In[1] = _042_ ? (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *) _037_[1] : 1'hx;
  assign d_In[2] = _042_ ? (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *) _037_[2] : 1'hx;
  assign d_In[3] = _042_ ? (* src = "contador.v:48|contador.v:23|<techmap.v>:445" *) _037_[3] : 1'hx;
  assign _003_[0] = Q[0] ^(* src = "contador.v:33|<techmap.v>:263" *)  1'h1;
  assign _038_[1] = _018_[1] ^(* src = "contador.v:33|<techmap.v>:263" *)  Q[0];
  assign _038_[2] = _019_[2] ^(* src = "contador.v:33|<techmap.v>:263" *)  _043_[1];
  assign _038_[3] = _019_[3] ^(* src = "contador.v:33|<techmap.v>:263" *)  _043_[2];
  assign _018_[1] = Q[1] ^(* src = "contador.v:33|<techmap.v>:262" *)  1'h1;
  assign _019_[3] = Q[3] ^(* src = "contador.v:33|<techmap.v>:262" *)  1'h1;
  assign _040_[1] = Q[1] &(* src = "contador.v:25|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _040_[2] = Q[2] &(* src = "contador.v:25|<techmap.v>:260|<techmap.v>:229" *)  _040_[1];
  assign _047_ = _019_[2] &(* src = "contador.v:41|contador.v:33|<techmap.v>:260|<techmap.v>:229" *)  _040_[1];
  assign _044_[2] = Q[2] |(* src = "contador.v:41|contador.v:33|<techmap.v>:260|<techmap.v>:229" *)  _047_;
  assign _045_ = _018_[1] &(* src = "contador.v:33|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _046_ = _019_[2] &(* src = "contador.v:33|<techmap.v>:260|<techmap.v>:229" *)  _043_[1];
  assign _043_[1] = Q[1] |(* src = "contador.v:33|<techmap.v>:260|<techmap.v>:221" *)  _045_;
  assign _043_[2] = Q[2] |(* src = "contador.v:33|<techmap.v>:260|<techmap.v>:229" *)  _046_;
  assign _020_[1] = MODO[1] ^(* src = "contador.v:41|contador.v:23" *)  1'h1;
  assign _020_[0] = MODO[0] ^(* src = "contador.v:33|contador.v:23" *)  1'h1;
  assign _034_[2] = _001_ &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _032_;
  assign _034_[1] = _002_ &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _031_;
  assign _034_[0] = _000_ &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _004_;
  assign _036_[12] = _003_[0] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _033_;
  assign _036_[13] = _003_[1] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _033_;
  assign _036_[14] = _003_[2] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _033_;
  assign _036_[15] = _003_[3] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _033_;
  assign _036_[8] = _003_[0] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _032_;
  assign _036_[9] = _038_[1] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _032_;
  assign _036_[10] = _038_[2] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _032_;
  assign _036_[11] = _038_[3] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _032_;
  assign _036_[4] = _003_[0] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _031_;
  assign _036_[5] = _003_[1] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _031_;
  assign _036_[6] = _039_[2] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _031_;
  assign _036_[7] = _039_[3] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _031_;
  assign _036_[0] = D[0] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _030_;
  assign _036_[1] = D[1] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _030_;
  assign _036_[2] = D[2] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _030_;
  assign _036_[3] = D[3] &(* src = "contador.v:48|contador.v:23|<techmap.v>:434" *)  _030_;
  assign _003_[1] = Q[1] ^(* src = "contador.v:25|<techmap.v>:263" *)  Q[0];
  assign _003_[2] = Q[2] ^(* src = "contador.v:25|<techmap.v>:263" *)  _040_[1];
  assign _003_[3] = Q[3] ^(* src = "contador.v:25|<techmap.v>:263" *)  _040_[2];
  assign _039_[2] = _019_[2] ^(* src = "contador.v:41|contador.v:33|<techmap.v>:263" *)  _040_[1];
  assign _039_[3] = _019_[3] ^(* src = "contador.v:41|contador.v:33|<techmap.v>:263" *)  _044_[2];
  assign _019_[2] = Q[2] ^(* src = "contador.v:41|contador.v:33|<techmap.v>:262" *)  1'h1;
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:66" *)
  FF DFF_0 (
    .CLK(CLK),
    .D(d_In[0]),
    .EN(ENB),
    .Q(Q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:67" *)
  FF DFF_1 (
    .CLK(CLK),
    .D(d_In[1]),
    .EN(ENB),
    .Q(Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:72" *)
  FF DFF_1bit (
    .CLK(CLK),
    .D(d_Out),
    .EN(ENB),
    .Q(RCO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:68" *)
  FF DFF_2 (
    .CLK(CLK),
    .D(d_In[2]),
    .EN(ENB),
    .Q(Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:69" *)
  FF DFF_3 (
    .CLK(CLK),
    .D(d_In[3]),
    .EN(ENB),
    .Q(Q[3])
  );
  assign _003_[31:5] = 27'h0000000;
  assign _006_[1] = _005_[1];
  assign _015_[1] = _005_[1];
  assign { _018_[3:2], _018_[0] } = { Q[3:2], Q[0] };
  assign _019_[1:0] = { _018_[1], _003_[0] };
  assign { _038_[30:4], _038_[0] } = { _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _003_[0] };
  assign { _039_[30:4], _039_[1:0] } = { _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _039_[31], _003_[1:0] };
  assign { _040_[31:3], _040_[0] } = { 28'h0000000, _003_[4], Q[0] };
  assign { _043_[30:3], _043_[0] } = { _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], _043_[31], Q[0] };
  assign { _044_[30:3], _044_[1:0] } = { _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _040_[1], Q[0] };
endmodule

(* top =  1  *)
(* src = "contador.v:77" *)
module contador16(CLK, ENB, MODO, entrada, salida, RCO, RCO162, RCO163, RCO164);
  wire [1:0] _00_;
  wire _01_;
  (* src = "contador.v:106" *)
  wire _02_;
  (* src = "contador.v:106" *)
  wire _03_;
  (* src = "contador.v:151" *)
  wire _04_;
  (* src = "contador.v:151" *)
  wire _05_;
  (* src = "contador.v:196" *)
  wire _06_;
  (* src = "contador.v:196" *)
  wire _07_;
  (* src = "contador.v:78" *)
  input CLK;
  (* src = "contador.v:79" *)
  input ENB;
  (* src = "contador.v:80" *)
  input [1:0] MODO;
  (* src = "contador.v:83" *)
  output RCO;
  (* src = "contador.v:84" *)
  output RCO162;
  (* src = "contador.v:85" *)
  output RCO163;
  (* src = "contador.v:86" *)
  output RCO164;
  (* src = "contador.v:102" *)
  wire clk2;
  (* src = "contador.v:148" *)
  wire clk3;
  (* src = "contador.v:193" *)
  wire clk4;
  (* src = "contador.v:81" *)
  input [15:0] entrada;
  (* src = "contador.v:103" *)
  wire modo11;
  (* src = "contador.v:149" *)
  wire modo113;
  (* src = "contador.v:194" *)
  wire modo114;
  (* src = "contador.v:82" *)
  output [15:0] salida;
  assign _01_ = _00_[0] |(* src = "contador.v:195" *)  _00_[1];
  assign modo11 = ~(* src = "contador.v:195" *) _01_;
  assign _02_ = CLK &(* src = "contador.v:106" *)  modo11;
  assign _03_ = RCO &(* src = "contador.v:106" *)  _01_;
  assign clk2 = _02_ |(* src = "contador.v:106" *)  _03_;
  assign _05_ = RCO162 &(* src = "contador.v:151" *)  _01_;
  assign _04_ = clk2 &(* src = "contador.v:151" *)  modo11;
  assign clk3 = _04_ |(* src = "contador.v:151" *)  _05_;
  assign _07_ = RCO163 &(* src = "contador.v:196" *)  _01_;
  assign _06_ = clk3 &(* src = "contador.v:196" *)  modo11;
  assign clk4 = _06_ |(* src = "contador.v:196" *)  _07_;
  assign _00_[0] = MODO[0] ^(* src = "contador.v:195" *)  1'h1;
  assign _00_[1] = MODO[1] ^(* src = "contador.v:195" *)  1'h1;
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:94" *)
  contador contador1 (
    .CLK(CLK),
    .D(entrada[3:0]),
    .ENB(ENB),
    .MODO(MODO),
    .Q(salida[3:0]),
    .RCO(RCO)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:140" *)
  contador contador2 (
    .CLK(clk2),
    .D(entrada[7:4]),
    .ENB(ENB),
    .MODO(MODO),
    .Q(salida[7:4]),
    .RCO(RCO162)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:185" *)
  contador contador3 (
    .CLK(clk3),
    .D(entrada[11:8]),
    .ENB(ENB),
    .MODO(MODO),
    .Q(salida[11:8]),
    .RCO(RCO163)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador.v:237" *)
  contador contador4 (
    .CLK(clk4),
    .D(entrada[15:12]),
    .ENB(ENB),
    .MODO(MODO),
    .Q(salida[15:12]),
    .RCO(RCO164)
  );
  assign modo113 = modo11;
  assign modo114 = modo11;
endmodule
